### ISSUE TITLE
Broken builds in CircleCI due to base64-encoded key

### ISSUE THREAD

**Issue by ndrewr** [sophienyaa/Dreamforce2018#1]
*Greeeat writeup and walkthru, thanks very much for both it and the DF presentation*.

OK, as for what happened, following all instructions and obtaining SERVER_KEY from the included build script, I noticed that the builds were breaking with an error message of `decode base64: invalid input`.

I looked carefully at the key string copy-pasted straight from the output on my terminal window and noticed that *spaces* were inserted at certain points corresponding to line breaks in the string output.

I manually removed the spaces, re-entered that env var into CircleCI and *boom* success!

Some googling around after seemed to indicate that adding the `-i` flag (ignore non-alpha-numerics) to the base64 command might also have mitigated the issue:

https://stackoverflow.com/a/15490765/2415751

I am unsure if this is an incident limited to me and my development machine. I am curious if I omitted some obvious step or environmental setting when generating the key. An interesting note: the same terminal command steps in the build script that broke on CircleCI *worked fine when repeated verbatim on my own machine*.

**Comment by sophienyaa** [comment]
Interesting, sorry I haven't seen this earlier. 

I've not seen this particular issue in any of my builds, but that is probably more down to being lucky with keys than anything else.

What was your local machine?

Regardless I will look into adding the -i flag to the scripts to try and mitigate further issues

**Comment by cmzhangxing** [comment]
@ndrewr 
I faced same problem in 2020/12 and fixed by: 
1.In create-scratch-org.sh, setup-prpd.sh, setup-uat.sh
Change 
echo $SFDC_SERVER_KEY | base64 -d > keys/server.key 
To
echo $SFDC_SERVER_KEY | base64 -di > keys/server.key

2.In Connected App > OAuth Policies >Permitted Users
Select "Admin approved users are pre-authorized"
Then In Connected App > Profiles > Add "System Administrator" profile

**Comment by szeitlin** [comment]
AFAICT, base64 on mac OSX doesn't have a `-i` option other than the one that corresponds to 
`--input` (meaning, input file). The current circleci docs say to use `base64 -w 0`, but `-w` doesn't seem to be a valid option, either.
